"""Creo tablas de Pokemon movimiento y equipo

Revision ID: bea46116e494
Revises: 
Create Date: 2025-11-29 21:30:44.741494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel      #1

# revision identifiers, used by Alembic.
revision: str = 'bea46116e494'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('efecto_movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('efecto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipo_nombre'), 'equipo', ['nombre'], unique=False)
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('base_experience', sa.Integer(), nullable=False),
    sa.Column('imagen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_nombre'), 'pokemon', ['nombre'], unique=False)
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_nombre'), 'tipo', ['nombre'], unique=True)
    op.create_table('estadistica',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('puntos_de_golpe', sa.Integer(), nullable=False),
    sa.Column('ataque', sa.Integer(), nullable=False),
    sa.Column('defensa', sa.Integer(), nullable=False),
    sa.Column('ataque_especial', sa.Integer(), nullable=False),
    sa.Column('defensa_especial', sa.Integer(), nullable=False),
    sa.Column('velocidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id')
    )
    op.create_table('evolucion',
    sa.Column('from_id', sa.Integer(), nullable=False),
    sa.Column('to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('from_id', 'to_id')
    )
    op.create_table('integrante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('apodo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('potencia', sa.Integer(), nullable=True),
    sa.Column('usos', sa.Integer(), nullable=False),
    sa.Column('precision', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('efecto_id', sa.Integer(), nullable=False),
    sa.Column('efecto_chance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_movimiento.id'], ),
    sa.ForeignKeyConstraint(['efecto_id'], ['efecto_movimiento.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimiento_nombre'), 'movimiento', ['nombre'], unique=False)
    op.create_table('pokemon_tipo',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'tipo_id')
    )
    op.create_table('type_efficacy',
    sa.Column('damage_type_id', sa.Integer(), nullable=False),
    sa.Column('target_type_id', sa.Integer(), nullable=False),
    sa.Column('damage_factor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['damage_type_id'], ['tipo.id'], ),
    sa.ForeignKeyConstraint(['target_type_id'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('damage_type_id', 'target_type_id')
    )
    op.create_table('integrante_movimiento',
    sa.Column('integrante_id', sa.Integer(), nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['integrante_id'], ['integrante.id'], ),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimiento.id'], ),
    sa.PrimaryKeyConstraint('integrante_id', 'movimiento_id')
    )
    op.create_table('pokemon_movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['move_id'], ['movimiento.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_movimiento_move_id'), 'pokemon_movimiento', ['move_id'], unique=False)
    op.create_index(op.f('ix_pokemon_movimiento_pokemon_id'), 'pokemon_movimiento', ['pokemon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_movimiento_pokemon_id'), table_name='pokemon_movimiento')
    op.drop_index(op.f('ix_pokemon_movimiento_move_id'), table_name='pokemon_movimiento')
    op.drop_table('pokemon_movimiento')
    op.drop_table('integrante_movimiento')
    op.drop_table('type_efficacy')
    op.drop_table('pokemon_tipo')
    op.drop_index(op.f('ix_movimiento_nombre'), table_name='movimiento')
    op.drop_table('movimiento')
    op.drop_table('integrante')
    op.drop_table('evolucion')
    op.drop_table('estadistica')
    op.drop_index(op.f('ix_tipo_nombre'), table_name='tipo')
    op.drop_table('tipo')
    op.drop_index(op.f('ix_pokemon_nombre'), table_name='pokemon')
    op.drop_table('pokemon')
    op.drop_index(op.f('ix_equipo_nombre'), table_name='equipo')
    op.drop_table('equipo')
    op.drop_table('efecto_movimiento')
    op.drop_table('categoria_movimiento')
    # ### end Alembic commands ###
